# Generated by Django 4.1.7 on 2023-03-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='wishes',
        ),
    ]
