# Generated by Django 4.1.7 on 2023-03-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_imagemodel_options_remove_product_wishes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageModel',
            new_name='Image',
        ),
    ]
