# Generated by Django 4.1.7 on 2023-03-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_comment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='negative_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='positive_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
