# Generated by Django 4.1.7 on 2023-03-16 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_comment_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='person',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.product'),
        ),
    ]
